### ISSUE TITLE
add a way to list titles by date added to nps database

### ISSUE THREAD

**Issue by gatosardina** [JK3Y/Swift-NPS-Browser#1]
that way it'll be easier to check the newly added titles

**Comment by gatosardina** [comment]
or maybe just a way to see the titles added in the last x hours/days?

**Comment by JK3Y** [comment]
Yeah that's something that I can implement. I'm not sure if you know this, but the title ids (which the list is sorted by) are incremental. The newest releases are going to be at the bottom of the list.

**Comment by JK3Y** [comment]
This was added in commit https://github.com/JK3Y/Swift-NPS-Browser/commit/bef3fb5f4df7d26cdbf5431e49be652a8a20d599#diff-ae82e50752909c84f986ea9b1416ae08
